### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by polyarkk** [Ciallo-Ani/surftimer#12]
过完整的一张图时，如果需要使用/tele回到某一关起点，应固定传送回原有起点位置，而不是/setstart设置的位置（<u>因为部分地图可以利用这一条来节省一些起步的时间</u>）

**Comment by Nyano1337** [comment]
是bug，[已修复](https://github.com/Ciallo-Ani/surftimer/commit/5ea6fe9e89209b5d1a4b9ddfdaa67d594accade4)，感谢提醒。
